Models/ViewModel/JobCard.cs
using System;
using System.Collections.Generic;

namespace freelancer.Models
{
    public class JobCard
    {
        public int jobId { get; set; }
        public string jobTitle { get; set; }
        public string jobsTypes { get; set; }
        public string location { get; set; }
        public Organizion postBy { get; set; }
        public EEmploymentType employmentType { get; set; }
        public float jobSalary { get; set; }
        public DateTime postDate { get; set; }
    }
}

Controllers/JobController.cs
using freelancer.Models;
using freelancer.Models.Services;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Hosting.Server;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;

namespace freelancer.Controllers
{
    
    public class JobController : Controller
    {
        private readonly JobServices jobServices;
        private readonly UserServices userServices;
        private readonly ApplicantsServices applicantsServices;
        private readonly IWebHostEnvironment env;




        private readonly SignInManager<UserModel> signInManager;

        public JobController(JobServices jobServices, UserServices userServices, SignInManager<UserModel> signInManager, ApplicantsServices applicantsServices, IWebHostEnvironment env)
        {
            this.jobServices = jobServices;
            this.userServices = userServices;
            this.signInManager = signInManager;
            this.applicantsServices = applicantsServices;
            this.env = env;

        }

        public IActionResult Book(int jobId)
        {
            var postJob = jobServices.GetJobById(jobId);
            string? userId = signInManager.UserManager.GetUserId(HttpContext.User);
            if (postJob == null || userId == null)
            {
                return NotFound();
            }
            if(userServices.isBooked(jobId, userId))
            {
                userServices.unBook(userId, postJob);
            }
            else
            {
                userServices.bookJob(userId, postJob);
            }
            
            return RedirectToAction("Index", "Home");
        }

        public IActionResult BookJobs()
        {
            string? userId = signInManager.UserManager.GetUserId(HttpContext.User);
            List<PostJob>? postJobs = userServices.userBookJobs(userId);
            if (postJobs == null)
            {
                return NotFound();
            }

            return View(postJobs);
        }

        public IActionResult MyJobs()
        {
            string? userId = signInManager.UserManager.GetUserId(HttpContext.User);
            if (userId == null)
            {
                return NotFound();
            }

            List<WorkingJob> myJobs = userServices.GetWorkingJobs(userId);

            return View(myJobs);
        }

        public IActionResult AppliedJobs()
        {
            string? userId = signInManager.UserManager.GetUserId(HttpContext.User);
            if (userId == null)
            {
                return NotFound();
            }
            List<PostJob> appliedJobs = applicantsServices.getUserAppliedJobs(userId);
            return View(appliedJobs);
        }

        // later chage to post, with cv upload
        public IActionResult ApplyJob(int jobid)
        {
            string? userId = signInManager.UserManager.GetUserId(HttpContext.User);
            var postJob = jobServices.GetJobById(jobid);
            if(postJob == null)
            {
                return NotFound();
            }
           if( applicantsServices.isApplyed(userId, postJob))
            {
                return RedirectToAction("Index", "Home");
            }
            applicantsServices.ApplyJob(userId, postJob);
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult UploadCv(CvUploadInput cvUploadInput)
        {
            var postJobId = Request.Form["postJobId"][0];

            string uploadLoc = "UserCVs";
            uploadLoc = Path.Combine(Path.GetTempPath(), uploadLoc);
            
            if (Request.Form.Files != null)
            {
                foreach (IFormFile upload in Request.Form.Files)
                {
                    
                    uploadLoc += Guid.NewGuid().ToString() + upload.FileName;
                    FileStream fileStream = new FileStream(uploadLoc, FileMode.Create);
                    upload.CopyTo(fileStream);
                    fileStream.Close();

                    string? userId = signInManager.UserManager.GetUserId(HttpContext.User);
                    if (userId == null || postJobId == null)
                    {
                        return NotFound();
                    }

                    applicantsServices.addCv(userId, int.Parse(postJobId), uploadLoc);
                }
                return RedirectToAction("Index", "Home");

            }

            else
            {
                return Content("heyyy");
            }
        }

        public IActionResult JobDetai(int jobId)
        {

            string? userId = signInManager.UserManager.GetUserId(HttpContext.User);
            PostJob postJob = jobServices.GetJobById(jobId);
            if (postJob == null || userId == null)
            {
                return NotFound();
            }
            ViewBag.postJobId = postJob.jobId;
            ViewBag.appledFlag = applicantsServices.isApplyed(userId,postJob);
            ViewBag.user = userServices.getUserWithColage(userId);


            return View(postJob);
        }

        public IActionResult viewPdf(string pdfUrl)
        {
            string ReportURL = pdfUrl;
            byte[] FileBytes = System.IO.File.ReadAllBytes(ReportURL);
            return File(FileBytes, "application/pdf");
        }


    }
}
 

Views/Shared/JobDetail.cshtml
<div class="JobDcontainer">

    <div class="nav">
        <div class="navHade">
            <img src="ellipse162941-qes2-200h.png" alt="Ellipse162941" class="avater" />
            <p class="title">Job Title</p>
        </div>

        <div class="icon-Group">
            <img src="vector2941-3fuj.svg" alt="Vector2941" class="icon" />
            <img src="vector2941-qt6j.svg" alt="Vector2941" class="icon" />
        </div>
    </div>


    <div class="main">

        <div class="text-bolck">
            <div class="title">
                company name
            </div>

            <div class="text">
                Lorem ipsum
            </div>
        </div>

        <div class="text-bolck">
            <div class="title">
                Positon
            </div>

            <div class="text">
                Lorem ipsum
            </div>
        </div>

        <div class="text-bolck">
            <div class="title">
                Location
            </div>

            <div class="text">
                Lorem ipsum
            </div>
        </div>

        <div class="text-bolck">
            <div class="title">
                Salary
            </div>

            <div class="text">
                Lorem ipsum
            </div>
        </div>

        <div class="text-bolck">
            <div class="title">
                Job Description
            </div>

            <div class="text">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                Curabitur efficitur dui feugiat est dapibus dignissim tempus eu
                m.Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                Curabitur efficitur dui feugiat est dapibus dignissim tempus eu
                m. zLorem ipsum dolor sit amet, consectetur adipiscing elit.
                Curabitur efficitur dui feugiat est dapibus dignissim tempus eu
                m.Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                Curabitur efficitur dui feugiat est dapibus dignissim tempus eu
                m
            </div>
        </div>

        <div class="text-bolck">
            <div class="title">
                Job Requirements
            </div>

            <li class="text list">
                Lorem ipsum
            </li>

            <li class="text list">
                Lorem ipsum
            </li>

            <li class="text list">
                Lorem ipsum
            </li>

        </div>

        <div class="text-bolck">
            <div class="title">
                Job Requirements
            </div>

            <div class="text">
                Lorem ipsum
            </div>
        </div>


        <div class="foot">
            <a class="btnn">Apply Now</a>
        </div>

    </div>

</div>

Views/Shared/_JobCard.cshtml
@model IJob


<link href="~/css/jobCard.css" rel="stylesheet" />

<div class="cardContainer">

    <div class="head">

        <p class="title"> @Model.jobTitle </p>

        <div class="cip">
            <p class="type"> @Model.jobsTypes </p>
        </div>

        <div class="book">
            <a class="navbar-brand" href="@Url.Action("Book", "Job" , new { jobId=Model.jobId })">
                <img class="icon" src="~/img/Vector.svg" />
             </a>
         
        </div>
    </div>

    <div class="body">

        <div class="org">
            <img class="avatar" src="https://i.pravatar.cc/150?img=@Model.postBy.institutionId"/>
            <p class="name"> @Model.postBy.name </p>

            <div class="iconGroup">
                <img src="~/img/Vector-3.svg" class="icon" />
                <img src="~/img/Vector-2.svg" class="icon" />
            </div>

        </div>

        <div class="jobInfo">
            <p class="loc">
                @Model.location
            </p>
            <p class="pr">
                @Model.employmentType | @Model.jobSalary BIRR
            </p>
        </div>

    </div>

    <div class="foot">
        <p class="time">
            @Model.postDate.ToShortDateString()
        </p>
        <a class="go" href="@Url.Action("JobDetai", "Job" , new { jobId=Model.jobId })">
            <img src="~/img/Vector-1.svg" class="icon" />
        </a>
    </div>

</div>

Views/Shared/_JobDetail.cshtml
@model PostJob;

<link href="~/css/JobDetai.css" rel="stylesheet" />


<div class="JobDcontainer">

    @if ((ViewBag.orgFlag == null))
    {
        <div class="nav">
        <div class="navHade">
            <img src="https://i.pravatar.cc/150?img=@Model.postBy.institutionId" class="avater" />
            <p class="title">@Model.jobTitle</p>
        </div>

        <div class="icon-Group">
            <img src="~/img/Vector-3.svg" alt="Vector2941" class="icon" />
            <img src="~/img/Vector-2.svg" alt="Vector2941" class="icon" />
        </div>
    </div>
    } 
    
    @if ((ViewBag.orgFlag != null))
    { 
     <div class="nav">
        <div class="navHade">
                <img src="https://i.pravatar.cc/150?img=@((ViewBag.applicant as UserModel).Id.ToCharArray().Sum(x => x)%10)" class="avater" />
                <p class="title">@((ViewBag.applicant as UserModel).fullName)</p>
        </div>

        <div class="icon-Group">
            <img src="~/img/Vector-3.svg" alt="Vector2941" class="icon" />
            <img src="~/img/Vector-2.svg" alt="Vector2941" class="icon" />
        </div>
    </div>
    }



    <div class="main">

        @if ((ViewBag.orgFlag == null))
        {
            <div class="text-bolck">
                <div class="title">
                company name
            </div>

            <div class="text">
                @Model.postBy.name
            </div>
        </div>
        }

        <div class="text-bolck">
            <div class="title">
                Positon
            </div>

            <div class="text">
                @Model.jobDuties
            </div>
        </div>

        <div class="text-bolck">
            <div class="title">
                Location
            </div>

            <div class="text">
                @Model.location
            </div>
        </div>

        <div class="text-bolck">
            <div class="title">
                Salary
            </div>

            <div class="text">
                @Model.jobSalary BIRR
            </div>
        </div>

        <div class="text-bolck">
            <div class="title">
                Job Description
            </div>

            <div class="text">
                @Model.jobDescription
            </div>
        </div>

        <div class="text-bolck">
            <div class="title">
                Job Requirements
            </div>

            <li class="text list">
                @Model.jobRequirements
            </li>


        </div>

        <div class="text-bolck">
            <div class="title">
                employment Type
            </div>

            <div class="text">
                @Model.employmentType
            </div>
        </div>

        <div class="foot">
            @if (ViewBag.orgFlag != null && ViewBag.orgFlag == true)
            {
                <a href="@Url.Action("accept", "Organizions" , new { applicantId=ViewBag.applicantId })" class="btnn"> Accept </a>
            }else
            {
                @if (ViewBag.appledFlag == null || ViewBag.appledFlag != true)
            {
                    <a href="@Url.Action("ApplyJob", "Job" , new { jobId=Model.jobId })" class="btnn">Apply Now</a>

                }
            else
                {
                    <p class="btnn">
                        in Progress
                    </p>
                }
            }

        </div>

    </div>

</div>

Views/Shared/_Layout.cshtml
@inject SignInManager<UserModel> signInManager;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - freelancer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>

    <header>
        <nav class="tempNav navbar navbar-expand-sm navbar-toggleable-sm border-bottom mb-3">
            <div class="container">
                <a class="navbar-brand Temptitle" asp-area="" asp-controller="Home" asp-action="Index">freelancer</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>*@
                        
                    </ul>
                   @* @if(signInManager.IsSignedIn(User)){
                        <form method="post" asp-action="LogOut" asp-controller="Account">
                            <li class="nav-item ml-auto">
                                <button type="submit" class="nav-link text-dark" >LogOut</button>
                            </li>
                        </form>
                    }else{
                        <li class="nav-item ml-auto">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                        </li>

                        <li class="nav-item ml-auto">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="LogIn">LogIn</a>
                        </li>

                       
                    }*@
                    @if (signInManager.IsSignedIn(User) && (ViewData["doseUserHaveCollage"] != null && (bool)ViewData["doseUserHaveCollage"] == false))
                        {
                        <li class="nav-item ml-auto">
                            <a class="nav-link tempa" asp-area="" asp-controller="Account" asp-action="RegisterCollage">Register Your Collage</a>
                        </li>
                    }
                    
                   
                </div>
            </div>
        </nav>


    </header>
    <div class="container-fluid">
        <div class="row">
        <div class="col-3" style="margin-left:auto;">
                @if (IsSectionDefined("ordSideBar"))
                {
                    @RenderSection("ordSideBar")
                }else{
                    @Html.Partial("_SideBar",await signInManager.UserManager.GetUserAsync(User))
                    

                }
        </div>
        <div class="col-4">
                <main role="main">
                    @RenderBody()
                </main>
        </div>
        <div class="col-3" style="margin-right:auto;">
                @if (IsSectionDefined("filtter"))
                {
                    @RenderSection("filtter")
                }
        </div>
        
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - freelancer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_OrganizionsSideBar.cshtml
@inject SignInManager<UserModel> signInManager;
@model Organizion

<link href="~/css/sideBar.css" rel="stylesheet" />


<div class="sideBarContainer">

    <div class="userBlock">

        <img class="avatar" src="https://i.pravatar.cc/150?img=@(Model.institutionId)">

        <div class="textBolce">

            <div class="groupIcon">
                <img class="icon" src="~/img/sdi/Vector-2.svg">

                <div class="nameBolck">
                    <p class="name">
                        @Model.name
                    </p>

                   
                </div>
            </div>


            <div class="groupIcon">
                <img class="icon" src="~/img/sdi/Vector.svg">

                <p class="email">
                    @Model.email
                </p>
            </div>

            <div class="groupIcon">
                <img class="icon" src="~/img/sdi/Vector-1.svg">
                <p class="phone">
                    @Model.phone
                </p>
            </div>
        </div>
    </div>

    <div class="tempPos">
        <div class="navtionText">
            Navigation
        </div>
        <div class="navtion">


            <div class="groupIcon endToend">
                <div class="navLineConta">
                    <a class="navLine" asp-area="" asp-controller="Organizions" asp-action="index">Applicants </a>
                </div>
                <img class="icon" src="~/img/sdi/Vector4.svg">
            </div>


            <div class="groupIcon endToend">
                <div class="navLineConta">
                    <a class="navLine" asp-area="" asp-controller="Organizions" asp-action="ListEmployees">List Employees</a>
                </div>
                <img class="icon" src="~/img/sdi/Vector4.svg">
            </div>
         

            <div class="groupIcon endToend">
                <div class="navLineConta">

                    @if (signInManager.IsSignedIn(User))
                    {
                        <form method="post" asp-action="LogOut" asp-controller="Account">

                            <button type="submit" class="navLine">LogOut</button>

                        </form>
                    }

                </div>
                <img class="icon" src="~/img/sdi/Vector4.svg">
            </div>



        </div>

    </div>


</div>

Views/Shared/_SideBar.cshtml
@inject SignInManager<UserModel> signInManager;
@model UserModel

<link href="~/css/sideBar.css" rel="stylesheet" />


<div class="sideBarContainer">

        <div class="userBlock">

        <img class="avatar" src="https://i.pravatar.cc/150?img=@(Model.Id.ToCharArray().Sum(x => x)%10)">

            <div class="textBolce">

                <div class="groupIcon">
                <img class="icon" src="~/img/sdi/Vector-2.svg">

                    <div class="nameBolck">
                        <p class="name">
                            @Model.fullName
                        </p>

                        <p class="">
                            |
                        </p>

                        <p class="userName">
                            @Model.UserName
                        </p>
                    </div>
                </div>


                <div class="groupIcon">
                <img class="icon" src="~/img/sdi/Vector.svg">

                    <p class="email">
                       @Model.Email
                    </p>
                </div>

                <div class="groupIcon">
                <img class="icon" src="~/img/sdi/Vector-1.svg">
                    <p class="phone">
                        @Model.PhoneNumber
                    </p>
                </div>
            </div>
        </div>

        <div class="tempPos">
        <div class="navtionText">
            Navigation
        </div>
        <div class="navtion">


            <div class="groupIcon endToend">
                <div class="navLineConta">
                    <a class="navLine" asp-area="" asp-controller="Home" asp-action="index">Home</a>
                </div>
                <img class="icon" src="~/img/sdi/Vector4.svg">
            </div>

            <div class="groupIcon endToend">
                <div class="navLineConta">
                    <a class="navLine" asp-area="" asp-controller="Job" asp-action="BookJobs">Book Jobs</a>
                </div>
                <img class="icon" src="~/img/sdi/Vector4.svg">
            </div>

            <div class="groupIcon endToend">
                <div class="navLineConta">
                    <a class="navLine" asp-area="" asp-controller="Job" asp-action="MyJobs">My Jobs</a>
                </div>
                <img class="icon" src="~/img/sdi/Vector4.svg">
            </div>

            <div class="groupIcon endToend">
                <div class="navLineConta">
                    <a class="navLine" asp-area="" asp-controller="Job" asp-action="AppliedJobs">Applied Jobs</a>
                </div>
                <img class="icon" src="~/img/sdi/Vector4.svg">
            </div>

            <div class="groupIcon endToend">
                <div class="navLineConta">
                    <a class="navLine" asp-area="" asp-controller="Organizions" asp-action="ListUserOrg">My Organization</a>
                </div>
                <img class="icon" src="~/img/sdi/Vector4.svg">
            </div>

            <div class="groupIcon endToend">
                <div class="navLineConta">
                    <a class="navLine" asp-area="" asp-controller="Organizions" asp-action="ListOrg">All Organization</a>
                </div>
                <img class="icon" src="~/img/sdi/Vector4.svg">
            </div>

            <div class="groupIcon endToend">
                <div class="navLineConta">

                   @if(signInManager.IsSignedIn(User)){
                        <form method="post" asp-action="LogOut" asp-controller="Account">

                            <button type="submit" class="navLine">LogOut</button>

                        </form>
                   }
             
                </div>
                <img class="icon" src="~/img/sdi/Vector4.svg">
            </div>

           

        </div>

        </div>


    </div>

Views/Shared/_applicantsCard.cshtml
@model UserModel;

<link href="~/css/applicantsCard.css" rel="stylesheet" />


<div class="ApplicantCardContainer">



    <div class="user">
        <img class="avatar" src="https://i.pravatar.cc/150?img=@(Model.Id.ToCharArray().Sum(x => x)%10)" />
        <p class="name">@Model.fullName </p>

        <div class="iocn-Group">
            <img src="~/img/Vector-3.svg" class="icon" />
            <img src="~/img/Vector-2.svg" class="icon" />
        </div>

    </div>

    <!-- <p class="tit">
        Collage
    </p> -->

    <div class="body">


        <div class="user body-nav">
            <img class="avatar" src="https://i.pravatar.cc/150?img=@(Model.collage.institutionId+10)" alt="">
            <p class="name">
                @Model.collage.name
            </p>
            <div class="iocn-Group">
                <img src="~/img/Vector-3.svg" class="icon" />
                <img src="~/img/Vector-2.svg" class="icon" />
            </div>
        </div>

    </div>

    <div class="foot">
      

        <div class="btn-Group">

            <a href="" class="btnn border noGo">
                <img src="~/img/wong.svg" class="icon" />

            </a>

            <a class="btnn go" href="@Url.Action("info", "Organizions" , new { applicantId=ViewBag.applicantId })">
                <img src="~/img/correct.svg" class="icon" />
            </a>
        </div>


    </div>
</div>

Views/Shared/_collageCard.cshtml
@model UserModel

<link href="~/css/collageCard.css" rel="stylesheet" />


<div class="collageCard">

    <div class="nav">
        <img class="avtar" src="https://i.pravatar.cc/150?img=@(Model.collage.institutionId+10)" alt="">
        <p class="name">
            @Model.collage.name
        </p>
        <div class="iocn-Group">
            <img src="~/img/Vector-3.svg" alt="Vector2941" class="icon" />
            <img src="~/img/Vector-2.svg" alt="Vector2941" class="icon" />
        </div>
    </div>

    <div class="main">

        <div class="text-bolck">
            <div class="title">
                    GPA
                </div>
                <p class="text">
                    @Model.student.GPA
                </p>
        </div>

        <div class="text-bolck">
            <div class="title">
                Skills
            </div>

           

            @foreach (var skill in Model.student.skills)
            {
                <li class="text list">
                    @skill.skillName
                </li>

               
            }

            

        </div>
    </div>

</div>

Views/Shared/_cvUpload.cshtml
@model CvUploadInput;

<link href="~/css/cVuploadCard.css" rel="stylesheet" />



    <form enctype="multipart/form-data" method="post" asp-action="UploadCv" asp-controller="Job" class="fileUploadCont">

    <input asp-for="postJobId" style="display: none;" value="@((ViewBag.postJobId??-1))">
    <label class="mask" for="fileUpload">
        <img class="icon" src="~/img/upload.svg" alt="">
    </label>
    <input type="file" name="file" class="input" id="fileUpload" accept="application/pdf" />

    <div class="foot">
        <button class="btnn" type="submit">
            Up Load
        </button>
    </div>
</form>

Views/Shared/_filterCard.cshtml
@model JobFilterInput;

<link href="~/css/filterCard.css" rel="stylesheet" />
<div class="tCon">
    <form method="POST" class="filttercontainer">

        <div class="salary from-Group">
            <label class="text" id="rangeText" for="range"> Salary from @((ViewData["initFilter"] as JobFilter).salary?.Start) </label>
            <input asp-for="salary" class="input" id="range" type="range" name="salary" min="@((ViewData["initFilter"] as JobFilter).salary?.Start)" max="100000" value="@((ViewData["initFilter"] as JobFilter).salary?.Start)">
            
        </div>

        <div class="location from-Group">
            <label class="text" for="location"> Location</label>
            <input asp-for="location" class="input" id="location" name="location" type="text" placeholder="enter location">
        </div>

        <div class="date from-Group">
            <label class="text" for="date">Post Date From</label>
            <input asp-for="postDate" class="input" type="date" name="postDate" id="date" min="@((ViewData["initFilter"] as JobFilter).postDate.Value.ToString(" yyyy-MM-dd"))" defaultValue="@((ViewData["initFilter"] as JobFilter).postDate.Value.ToString(" yyyy-MM-dd"))">
            </div>

            <div class="skills from-Group">
     
                <label class="text" for="date">skills</label>
            @Html.DropDownList(
            "skills",
        ViewBag.selectSkillsList,
        "Select skill",
        new { @class = "input" })
            </div>

            <div class="foot">
                <button class="button reset" type="reset">
                    <img class="icon" src="~/img/Reset.svg" alt="" srcset="">
                </button>

                <button class="button submit" type="submit">
                    <img class="icon" src="~/img/Submit.svg" alt="" srcset="">
                </button>
            </div>

        </form>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script>
        $("#range").change(()=>{
            console.log("change")
            $("#rangeText").text("Salary from "+$("#range").val())

        })
    </script>

Views/Shared/_orgCard.cshtml
@model Organizion

<link href="~/css/orgCard.css" rel="stylesheet" />

<div class="Orgcontainer">

    <div class="nav">
        <img class="avtar" src="https://i.pravatar.cc/150?img=@Model.institutionId" alt="">
        <p class="name">
            @Model.name
        </p>
        <div class="iocn-Group">
            <img class="icon" src="~/img/Vector-3.svg" alt="">
            <img class="icon" src="~/img/Vector-2.svg" alt="">
            <img class="icon" src="~/img/like.svg" alt="">
        </div>
    </div>

    <div class="main">

        <div class="workCount">
            <p class="title">
                Post Work
            </p>
            <p class="conut">
                @Model.postedJobs.Count()
            </p>
        </div>

        <div class="workCount">
            <p class="title">
                Active Work
            </p>
            <p class="conut">
                @Model.activeJobs.Count()
            </p>
        </div>

        <div class="workCount">
            <p class="title">
                Concluded Work
            </p>
            <p class="conut">
                @Model.DoneJobs.Count()
            </p>
        </div>

    </div>
</div>

Views/Shared/_userCard.cshtml
@model UserModel;

<link href="~/css/applicantsCard.css" rel="stylesheet" />


<div class="ApplicantCardContainer">



    <div class="user">
        <img class="avatar" src="https://i.pravatar.cc/150?img=@(Model.Id.ToCharArray().Sum(x => x)%10)" />
        <p class="name">@Model.fullName </p>

        <div class="iocn-Group">
            <img src="~/img/Vector-3.svg" class="icon" />
            <img src="~/img/Vector-2.svg" class="icon" />
        </div>

    </div>

    <!-- <p class="tit">
        Collage
    </p> -->

    <div class="body">

    </div>


</div>